clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:innius/grafana-video-panel.git

  tags:
    v*:
      - step:
          script:
            - git push git@github.com:innius/grafana-video-panel.git --tags
