version: '3.3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
        
      - GF_INSTALL_PLUGINS=https://github.com/innius/grafana-video-panel/releases/download/v1.0.4/innius-video-panel-1.0.4.zip;innius-video-panel
    restart: always



